Added documentation for Extended Crafting
CleanroomMC/GroovyScript-Docs pull request #13
Opened 2023-06-19 13:59 UTC by JuiceyBeans

Note: Table crafting is not added yet

2023-06-20 06:58 UTC, WaitingIdly requested changes
1. the wiki isnt just markdown, it uses a specialized format for mkdocs. youll need to test this using the instructions in the readme.
2. you have to add the file locations to the `mkdocs.yml`
3. file names should be `snake_case`
4. text you want in a `!!!` block must be indented
5. there should be an empty line after each title/subtitle
6. include the package name for the packages, eg my example below
7. instead of an `### Example`, use an `!!! example`. 


````
Package:

```groovy
mods.extendedcrafting.Combination
mods.extendedcrafting.CombinationCrafting
```
````

2023-06-20 06:58 UTC, WaitingIdly commented on docs/groovyscript/mods/extendedcrafting/compressioncrafting.md
> +## Removing recipes
i would suggest using a format like the one used for the Blood Altar, where it states what it does and then has a codeblock of the function call

https://github.com/juraj-hrivnak/GroovyScript-Docs/blob/746254fe18bd693bbc710784489cfa0e4a7891f1/docs/groovyscript/mods/bloodmagic/blood_altar.md?plain=1#L91

2023-06-25 06:40 UTC, brachy84 requested changes

2023-06-25 06:40 UTC, brachy84 commented on docs/groovyscript/mods/extendedcrafting/combination_crafting.md
> +mods.extendedcrafting.combination.recipeBuilder(ItemStack output, long cost, int perTick, Ingredient input, NonNullList<Ingredient> pedestals)
`add` not `recipebuilder`

2023-06-25 06:40 UTC, brachy84 commented on docs/groovyscript/mods/extendedcrafting/combination_crafting.md
> +mods.bloodmagic.CombinationCrafting.removeAll()
bloodmagic?

2023-06-25 06:40 UTC, brachy84 commented on docs/groovyscript/mods/extendedcrafting/compression_crafting.md
> +mods.extendedcrafting.compression.recipeBuilder(ItemStack output, IIngredient input, int inputCount, IIngredient catalyst, boolean consumeCatalyst, int powerCost, int powerRate)
combination? recipeBuilder?

2023-06-25 06:51 UTC, WaitingIdly commented on docs/groovyscript/mods/extendedcrafting/combination_crafting.md
> +mods.bloodmagic.CombinationCrafting.removeAll()
oh whoops that ones on me

2024-02-17 13:47 UTC, closed without merging

2024-02-17 13:47 UTC, brachy84 commented
superseeded by #18