Merge thaumcraft groovyscript compat documentation
CleanroomMC/GroovyScript-Docs pull request #4
Opened 2022-12-17 00:12 UTC by Wong-Innovations

2022-12-23 20:51 UTC, WaitingIdly requested changes

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/ArcaneWorkbench.md
> +### Adding Shaped Recipes
undocumented features: `mirrored`, `row`

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/ArcaneWorkbench.md
> +.aspect(AspectStack) // must be a primal aspect
should list the primal aspects in an annotation

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/ArcaneWorkbench.md
> +.aspect(AspectStack) // must be a primal aspect
should list the primal aspects in an annotation

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/ArcaneWorkbench.md
> +.vis(int) // (1)
if you do 
```suggestion
.vis(int/*(1)!*/)
```
instead it will appear like this [image]. might be worth considering, i really like the effect. would apply in a fair number of other places

![image](https://user-images.githubusercontent.com/25394029/209327084-b40327ab-d999-49b7-9e90-2a5b2ae99ed6.png)

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/ArcaneWorkbench.md
> +1. Please see the examples below to better understand how this works
i dont think the documentation below helps explain this enough. wouldnt this be really simple to explain, too? just 
```
The Research Key is the required research to craft the item, research is unlocked via the Thaumonomicon. Obtain a list of all research keys by doing `/thaumcraft research list`.
```
(command may be incorrect).
should be applied to all cases where this "read the examples" appears, which is most pages.

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/Aspects.md
> +`aspect('<latin aspect name>')` when no <amount> is specified the default value is 1
![image](https://user-images.githubusercontent.com/25394029/209328379-c6a118b1-2ac2-478a-8463-536fbfed684c.png)

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/Aspects.md
> +Adding component aspects: (2 required)
```suggestion
Adding component aspects: (requires either exactly 0 or exactly 2)
```
(this might be incorrect, in which case this is optional. the API accepts it, but has specific checks for 0 and 2)

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/Aspects.md
> +.component(AspectStack) // name of the new aspect
aspects of the required aspects

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/Aspects.md
> +2. Please see the examples below to better understand how this works
explain via something like "gets the resource location via `mod + ":" + path`. without it, it gets `"thaumcraft:" + path`"

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/Aspects.md
> +.chatColor(int)
what format is the int? how does it get the color from the int?

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/Aspects.md
> +Set target entity: (required, entity only)
can you more clearly indicate that only one of these may be used?

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/Aspects.md
> +// set chicken's to have 20 bestia essentia
```suggestion
Set chickens to have 20 Bestia Essentia
```

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/Aspects.md
> +// set all stone blocks to have 20 ignis essentia
```suggestion
// set all Stone blocks to have 20 Ignis Essentia
```

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/DustTrigger.md
> +.researchKey(String)  // (1)
this actually does display with two spaces
```suggestion
.researchKey(String) // (1)
```

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/Infusion.md
> +Adding mainInput: (requires exactly 1)
could what this means and why its different from just `input` be explained?

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/Research.md
> +A research builder has yet to be created, for now this method takes in a json representation of the thaumonomicon tab's research.
could you admonition this as like `!!! danger "experimental"`

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/Research.md
> +                "category": "BASICS", "location": [ 0,0 ],
should have a line break here

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/Lootbag.md
> +Removes all items from the specified rarity of lootbag (except broken armor which is hard coded into randomized loot function).
can you add
```
!!! Bug
    Armor is hard coded into a randomized loot function, and not removed.
```

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/Lootbag.md
> +Each lootbag modification is rarity specific. Rarities can be specified using the following methods
missing period

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/Research.md
> +The following methods allow for scanning a specified Object with a thaumometer to discover the Object's component aspects.
Thaumometer

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/Research.md
> +mods.thaumcraft.Research.addScannable(Material)
what is a "Material"? the others are all understandable (note: we should definitely get bracket handlers for them)

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/SmeltingBonus.md
> +Add or remove bonus outputs from the infernal furnace
```suggestion
Add or remove bonus outputs from the Infernal Furnace. 
```

2022-12-23 20:51 UTC, WaitingIdly commented on docs/groovyscript/mods/thaumcraft/SmeltingBonus.md
> +.input(IIngredient)
include a note about how the input must be a valid furnace input to work

2022-12-23 20:51 UTC, WaitingIdly commented on mkdocs.yml
> +                - Arcane Workbench: groovyscript\mods\thaumcraft\ArcaneWorkbench.md
change these to `/`

2022-12-23 20:51 UTC, WaitingIdly commented on mkdocs.yml
> +    - def_list
`def_list` also appears 6 lines down

2023-01-06 09:00 UTC, Wong-Innovations commented on docs/groovyscript/mods/thaumcraft/Research.md
> +A research builder has yet to be created, for now this method takes in a json representation of the thaumonomicon tab's research.
tested, I did not like the visual result. opting to denote [WIP] as other doc pages do.

2023-01-06 09:03 UTC, Wong-Innovations commented on docs/groovyscript/mods/thaumcraft/Research.md
> +mods.thaumcraft.Research.addScannable(Material)
Material is derived from the package: net.minecraft.block.material. This feature has been implemented and documented even though there is no Material bracket handler yet so once one is created the docs will not need to be updated.

2023-02-05 21:43 UTC, merged